[build]
  functions = "netlify/functions"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
